### ISSUE TITLE
Contribute to an existing trait database?

### ISSUE THREAD

**Issue by seltmann** [willpearse/natdb#95]
@willpearse I am wondering if there is an existing MADtraits db that it makes sense for us to contribute. Is there a list of existing instances of MADtraits to examine.

This is for https://github.com/Extended-Bee-Network/bee-interaction-database

Thank you!

**Comment by willpearse** [comment]
Thanks for following up after our meeting! I'm not quite sure I understand your question, so sorry if the below isn't very helpful.

To set up MADtraits and download all the different data it can synthesise, run (from within R):

```{R}
library(devtools)
install_github("ropensci/suppdata") # (We need to get a new version of this package on CRAN)
install_github("willpearse/MADtraits")
```

...then, to grab all the trait data, make a folder somewhere on your computer to house the data it loads (mine is `~/Code/MADtraits/cache`), and then run:

```{R}
library(MADtraits)
data <- MADtraits("~/Code/MADtraits/cache")
```

...you should, eventually, then have all the data loaded on your computer. Once you've done it once, running the same line above will be much faster because the data is cached.

For examples of how to load data from existing sources into MADtraits (i.e., to link your, or someone else's, data into it) take a look at https://github.com/willpearse/MADtraits/wiki or take a look at one of the many other datasets loaded in at https://github.com/willpearse/MADtraits/blob/master/R/downloads.R#L35. Does that help?

**Comment by seltmann** [comment]
Yes! this does help. I will be sure to have more questions once I try it a bit.
